### ISSUE TITLE
Setup Guide for Validators

### ISSUE THREAD

**Issue by IstoraMandiri** [kovan-testnet/proposal#1]
To Start off: 

* Parity Config File

And then potentially

* Docker 
* Azure Marketplace App

Also, what are best practices for validator node redundancy, and how should keys be managed for redundant nodes?

**Comment by awrelll** [comment]
Waiting for it ! Great job @hitchcott 👍

**Comment by IstoraMandiri** [comment]
https://github.com/kovan-testnet/config
